services:
    domaindive:
        build: .
        volumes:
            - domaindive_data:/app/db
        ports:
            - "4000:4000"
        env_file: .env
        restart: unless-stopped

volumes:
    domaindive_data:
